import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar/page";
import Footer from "../components/footer/page";
import Providers from "./providers";
import SlideCard from "@/components/SlideCard/SlideCard";
import Size from "@/components/Size/Size";
import Hambarger from "@/components/Hambarger/Hambarger";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Estarch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body className={`${inter.className} bg-base-100 `}>
        <Providers>
          <NavBar />
          <Hambarger/>
          <SlideCard/>
          <Size/>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
