

import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar/page";
import Footer from "../components/footer/page";
import Providers from "./providers";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
