import Sidebar from "@/components/sidebar/Sidebar";
import { Inter } from "next/font/google";
import { FaRegUserCircle } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Estarch",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="grid grid-cols-12 md:mx-12 my-4 ">
      <div className="breadcrumbs text-sm col-span-2">
        <ul>
          <li><a>Home</a></li>
          <li><a>My Account</a> </li>
        </ul>
      </div>
      <div className="col-span-10">
        <h1 className="flex items-center gap-4 text-2xl font-bold"><span className="text-4xl"><FaRegUserCircle /></span>Hello, USER</h1>
      </div>
      <div className="col-span-2 mt-6 mr-4"><Sidebar /></div>
      <div className="col-span-10 mt-6">{children}</div>
    </div>
  );
}
